name: tourguideapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.1.2
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  dots_indicator: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  animate_do: ^3.3.4
  flutter_facebook_auth: ^7.1.1
  http: ^1.2.2
  like_button: ^2.0.5
  image_picker: ^1.1.2
  geolocator: ^13.0.1 
  flutter_xlider: ^3.5.0
  flutter_plugin_android_lifecycle: ^2.0.23
  mapbox_search: ^4.2.2
  pin_code_fields: ^8.0.1
  intl_phone_number_input: ^0.7.4
  firebase_app_check: ^0.3.1+7
  flutter_bloc: ^9.0.0
  shimmer: ^3.0.0
  video_player: ^2.9.5
  youtube_player_flutter: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  flutter_google_places_sdk: ^0.4.2+1
  flutter_dotenv: ^5.2.1
  mapbox_maps_flutter: ^2.0.0
  uuid: ^4.5.1
  geocoding: ^4.0.0
  google_generative_ai: ^0.2.0
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.12
  momo_vn:
    path: packages/momo_vn

  # Localization dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  linear_step_indicator: ^1.0.0+3

  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/img/
    - .env
