name: tourguideapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.1.2
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1

  # Localization dependencies
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
